runtime: python37

entrypoint: gunicorn -b :$PORT application:application

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /favicon.ico
  static_files: static/sfavicon.ico
  upload: static/favicon.ico
  secure: always

- url: /.*
  script: auto
  secure: always

env_variables:
  MAIL_PASS: Rema123123!
  DB_PASS: Rema123123!
  DB_CONNECTION: myfitnessdiary:us-east1:myfitnessdiary
