runtime: python37

entrypoint: gunicorn -b :$PORT flaskr:app

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always

- url: /.*
  script: auto
  secure: always

env_variables:
  MAIL_PASS: Rema123123!
  DB_PASS: Rema123123!
  DB_CONNECTION: localhost
  CLOUD_STORAGE_BUCKET: birmingham4test.appspot.com